### ISSUE TITLE
X-Frame options header is not includled in response - potentially vulnerable to clickjacking attacks

### ISSUE THREAD

**Issue by whaber** [covidwatchorg/portal#422]
Portal is potentially vulnerable to clickjacking attacks (AKA UI Redress attacks).  The portal can be rendered inside of an xframe of another application.

Example on how to solve here: https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html

Basically adding this to the headers:

`Content-Security-Policy: frame-ancestors 'none';
`

>  This prevents any domain from framing the content. This setting is recommended unless a specific need has been identified for framing.

**Comment by ibeckermayer** [comment]
Same Firebase cloud functions issues as my other responses. Maybe we should open these issues with Firebase? It sounds like some of these ought to be defaults.

**Comment by whaber** [comment]
In the interim, this looks like a potential workaround: https://stackoverflow.com/questions/42934203/firebase-header-csp-rules

**Comment by whaber** [comment]
FWIW, I filed a bug with Google (Case 00075892) to get their thoughts on making this easier for all users of Firebase.

**Comment by colbymorrison** [comment]
I believe this doesn't have to do with Firebase, since this is about HTTP headers and we don't use Firebase to serve our HTTP/host our website. We use AWS S3/CloudFront to host our site and serve the HTTP. So, we need to set the `Content-Security-Policy` header in AWS. [Here](https://www.savjee.be/2018/05/Content-security-policy-and-aws-s3-cloudfront/) is a guide on how to do this, and [here](https://aws.amazon.com/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/) are the detailed AWS docs on this. Unfortunately, we can't do this directly in S3, it requires setting up a Lambda function, but may be worth doing in the interest of security.

**Comment by colbymorrison** [comment]
Added to staging
<img width="1275" alt="Screen Shot 2020-08-27 at 9 21 10 PM" src="https://user-images.githubusercontent.com/20446774/91520934-7056a680-e8ab-11ea-8442-900aa9823b4e.png">

**Comment by colbymorrison** [comment]
New headers now in production! Closing this issue.
